### ISSUE TITLE
Cannot Install Feed in v18.0.01

### ISSUE THREAD

**Issue by omarali-me** [GibbonEdu/module-feed#2]
![image](https://user-images.githubusercontent.com/47008784/69429394-dfb3ce80-0d4c-11ea-9599-cdf3b568a4d4.png)

I downloaded module-feed from the website and then from github (here) and put the folder in the modules folder but i get the error (as you can see from the mini-screenshot)..

I have done the same with other modules and it worked well..

**Comment by rossdotparker** [comment]
Hi @omarali-me, thanks for sharing this. I've tried to recreate the issue, but have not been able to. Please can you check that the name of the folder in /modules matches the name of the module in the module's manifest.php. Both of these values should be "Feed". Thanks!

**Comment by omarali-me** [comment]
Ah... Hmmm I think it was downloading as feeds instead of feeds



Regards



Omar Ali Ibrahim



https://omarali.me








---- On Sun, 24 Nov 2019 05:35:07 +0400 notifications@github.com wrote ----



Hi @omarali-me, thanks for sharing this. I've tried to recreate the issue, but have not been able to. Please can you check that the name of the folder in /modules matches the name of the module in the module's manifest.php. Both of these values should be "Feed". Thanks!

**Comment by omarali-me** [comment]
Nope, it's Feed in both situations (folder name) and the manifest.php file..

**Comment by rossdotparker** [comment]
Compatibility should be v17+. Are you using v18.0.01? I've tested it in v19.0.00 and it is working fine.

Are you able to share a screenshot of the contents of your /modules folder?

**Comment by omarali-me** [comment]
Yes, I'm using v18.0.01.

![image](https://user-images.githubusercontent.com/47008784/69535445-61963880-0f95-11ea-9bc3-1fb334bb3921.png)

![image](https://user-images.githubusercontent.com/47008784/69535453-6b1fa080-0f95-11ea-8e02-bb738ce24a8c.png)


![image](https://user-images.githubusercontent.com/47008784/69535470-75419f00-0f95-11ea-98a2-e54bef70da6b.png)

**Comment by rossdotparker** [comment]
Hmmm. I'm not sure, so I'll need your help to investigate further, if that is OK? To do this, open the file /modules/System Admin/module_manage.php. The error you are seeing is generated on line 109 because of the logic on line 106. Can you add print_r($module); to line 105, and then reload the page. At the top of the page you should get the output of the array $module. Can you copy and paste that here? Thanks!

**Comment by omarali-me** [comment]
Hello Ross... I'm sorry I never got around to following your instructions because I got busy figuring out the rest of the system :) So, I am now getting around to doing it.. and I already have a sense of what the problem might be... 

Array ( [name] => [description] => [entryURL] => [type] => [category] => [version] => [author] => [url] => [manifestOK] => [status] => Not Installed [versionDisplay] => )

It seems it's empty for some reason

**Comment by rossdotparker** [comment]
Hmmm, that is interesting. This array is populated by the function declared on line 107 of /modules/System Admin/moduleFunctions.php. Are you able to see what part of this function is not behaving as expected?

**Comment by omarali-me** [comment]
I am SO SORRY Mr. Ross. I had completely forgotten to give the folders the correct user-rights ! :)

**Comment by rossdotparker** [comment]
No need to apologise at all. An easy mistake to make, and I am sure this post will help someone in the future. Glad to hear you got it sorted.
